# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  displayName: 'Install Java 17'
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dmaven.test.failure.ignore=false'
    javaHomeOption: 'JAVA_HOME'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'

- script: |
    echo JAVA_HOME is $JAVA_HOME
    java -version
    mvn -version
  displayName: 'Check Java and Maven Version'